version = 1
SPDX-PackageName = "opendatahub-content-api-core"
SPDX-PackageSupplier = "NOI Techpark <digital@noi.bz.it>"
SPDX-PackageDownloadLocation = "https://github.com/noi-techpark/opendatahub-content-api-core"

[[annotations]]
path = [".github/**", "infrastructure/**", ".gitignore", ".pre-commit-config.yaml", ".dockerignore", ".env.example", ".gitmodules", "docker-compose.dcproj", "opendatahub-content-api-core.sln", "**/**.csproj", "**/**.fsproj", "**/appsettings.**", "**/Dockerfile", "**/Properties/**.json", "ContentApiCoreTests/xunit.runner.json", "ContentApiCore/wwwroot/images/**", "ContentApiCore/wwwroot/json/**", "ContentApiCore/docker/**", "GeoConverterTests/Files/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) NOI Techpark <digital@noi.bz.it>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["ContentApiCore/wwwroot/**/**.min.**", "ContentApiCore/pages/Index.cshtml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) NOI Techpark <digital@noi.bz.it>"
SPDX-License-Identifier = "AGPL-3.0-or-later"
