name: CI/CD API

on:
  push:
  pull_request:

env:
  PROJECT_NAME: odh-content-api
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}-api
  DOCKER_TAG: ${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        dotnet-quality: 'preview'
    - name: Restore dependencies
      run: dotnet restore opendatahub-content-api-core.sln
    - name: Build opendatahub-content-api-core Solution
      run: dotnet build opendatahub-content-api-core.sln --no-restore
    - name: Test
      run: dotnet test ContentApiCore --filter Category!=Integration

  # deploy-test-api:
    # runs-on: ubuntu-20.04
    # if: github.ref == 'refs/heads/main'
    # env:
      # API_URL: "https://api.tourism.testingmachine.eu/v1/"
    # needs: test
    # concurrency: deploy-test-api
    # steps:
      # - name: Checkout source code
        # uses: actions/checkout@v2
        # with:
          # submodules: true

      # - name: Create .env file
        # uses: noi-techpark/github-actions/env-file@v2
        # env:
          # X_COMPOSE_PROJECT_NAME: ${{ env.PROJECT_NAME }}
          # X_DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
          # X_DOCKER_TAG: ${{ env.DOCKER_TAG }}
          # X_SERVER_PORT: 1011

          # X_ASPNETCORE_ENVIRONMENT: "Development"
          # X_PG_CONNECTION: ${{ secrets.PG_CONNECTION_TEST }}

      # - name: Setup config
        # run: |
            # echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_NOICOMMUNITY }}" > google-service-account.noicommunity.json
            # chmod +r google-service-account.noicommunity.json

      # - name: Build and push 
        # uses: noi-techpark/github-actions/docker-build-and-push@v2
        # with:
          # docker-username: ${{ github.actor }}
          # docker-password: ${{ secrets.GITHUB_TOKEN }}
          # working-directory: OdhApiCore
          # docker-compose-file: docker-compose.yml

      # - name: Deploy application
        # uses: noi-techpark/github-actions/docker-deploy@v2
        # with:
          # hosts: 'test'
          # ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          # docker-username: 'noi-techpark-bot'
          # docker-password: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          # project-name: ${{ env.PROJECT_NAME }}

      # - name: Generate Json
        # run: |
          # curl "${{ env.API_URL }}STA/JsonPoi"
          # curl "${{ env.API_URL }}STA/JsonAccommodation"
          # curl "${{ env.API_URL }}ODH/AccommodationBooklist"
          # curl "${{ env.API_URL }}ODH/AccommodationFulllist"
          # curl "${{ env.API_URL }}ODH/Taglist"
          # curl "${{ env.API_URL }}ODH/OdhTagAutoPublishlist"
          # curl "${{ env.API_URL }}ODH/OdhTagCategorieslist"
          # curl "${{ env.API_URL }}ODH/WeatherForecast"